name: CI/CD Pipeline - DevOps na Prática

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_cd:
    runs-on: ubuntu-latest

    steps:
      #Checkout
      - name: Checkout do código
        uses: actions/checkout@v4

      #Node.js (CI)
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install || echo "Sem dependências para instalar"

      - name: Validar HTML
        run: |
          test -f ./src/index.html || (echo "index.html ausente!" && exit 1)
          grep -q "<html" ./src/index.html || exit 1
          grep -q "</html>" ./src/index.html || exit 1
          echo "HTML válido ✔️"

      #Build Docker
      - name: Construir imagem Docker
        run: docker build -t devops-app -f docker/Dockerfile .

      #Testar container
      - name: Testar container
        run: |
          docker run -d -p 8080:80 --name devops-container devops-app
          sleep 3
          docker ps | grep devops-container || (echo "Falha ao iniciar container" && exit 1)
          docker stop devops-container

      #Configurar AWS
      - name: Configurar AWS opcional
        id: awscreds
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      #Deploy no S3 (somente se AWS estiver ativa)
      - name: Deploy no S3
        if: steps.awscreds.outcome == 'success'
        run: |
          echo "Deploy para o S3 iniciado..."
          aws s3 cp src/index.html s3://devops-na-pratica-erico-site/index.html --acl public-read
          echo "Deploy finalizado com sucesso ✔️"

      #Upload de artefatos
      - name: Upload do Dockerfile como artefato
        uses: actions/upload-artifact@v4
        with:
          name: dockerfile
          path: docker/Dockerfile

      - name: Upload do compose
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker/docker-compose.yml

      - name: Finalização
        run: echo "Pipeline finalizado sem erros! ✔️"
